# Cho phép kết nối từ thiết bị khác (điện thoại thật)
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3306/weconnect_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=121930
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=WeConnectSecretKey2026SuperSecureRandomStringForJWTTokenGeneration123456
jwt.expiration=86400000